services:
  db:
    image: mongo:7.0-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' db:${DB_PORT}/${DB_NAME} --quiet
      interval: 40s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./data/database:/data/db
      - ./database/initdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app
  cms:
    build:
      context: ./cms
    image: ${REGISRTY}/cms
    restart: always
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST=db
      - DB_PORT
      - PORT=${CMS_PORT}
      - PAYLOAD_SECRET=${CMS_SECRET}
    healthcheck:
      test: node /home/node/app/healthcheck.js
      interval: 20s
      timeout: 5s
      start_period: 50s
      retries: 3
    ports:
      - ${CMS_PORT}:${CMS_PORT}
    volumes:
      - ./data/cms:/home/node/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app
  client:
    build:
      context: ./front
    image: ${REGISRTY}/client
    restart: always
    environment:
      - GRAPHQL_HOST=http://cms:${CMS_PORT}/api/graphql
      - APP_DOMAIN=https://www.${APP_DOMAIN}
    depends_on:
      cms:
        condition: service_healthy
    networks:
      app:
  gateway:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_DOMAIN
      - CLIENT=client:4321
      - CMS=cms:${CMS_PORT}
      - CERTIFICATES_FOLDER
    volumes:
      - ./network/nginx.conf:/etc/nginx/templates/default.conf.template:ro 
      - ./network/certificates:${CERTIFICATES_FOLDER}:ro
    depends_on:
      cms:
        condition: service_healthy
    networks:
      - app

networks:
  app:
