
upstream client {
  server ${CLIENT};
}

upstream cms {
  server ${CMS};
}

upstream objects {
  server ${OBJECTS};
}

server {
  listen 80;
  server_name ${APP_DOMAIN};

  return 301 https://${APP_DOMAIN}$request_uri;
}

server {
  listen 80;
  server_name admin.${APP_DOMAIN};

  return 301 https://admin.${APP_DOMAIN}$request_uri;
}

server {
  listen 443 ssl;
  server_name ${APP_DOMAIN};

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  ssl_certificate ${CERTIFICATES_FOLDER}/certificate.crt;
  ssl_certificate_key ${CERTIFICATES_FOLDER}/certificate.key;

  location / {
    proxy_pass http://client;
    proxy_redirect     off;
  }
}

server {
  listen 443 ssl;
  server_name admin.${APP_DOMAIN};

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  ssl_certificate ${CERTIFICATES_FOLDER}/certificate.crt;
  ssl_certificate_key ${CERTIFICATES_FOLDER}/certificate.key;

  location / {
    proxy_pass http://cms;
    proxy_redirect     off;
  }
}

server {
  listen 443 ssl;
  server_name cdn.${APP_DOMAIN};

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  ssl_certificate ${CERTIFICATES_FOLDER}/certificate.crt;
  ssl_certificate_key ${CERTIFICATES_FOLDER}/certificate.key;

  location / {
    proxy_pass http://objects/${S3_BUCKET}/;
    proxy_redirect     off;
    proxy_cache_valid 200 10m;
    proxy_cache_valid 404 1m;
    proxy_cache_background_update on;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
  }
}